suggestion:
  suggestionData:
    population_density_com:
      urlQueryParams:
        numReturn: number
      requestAttributes:
        location: dropdown
        date: start date 1 year getting the data from this date until present
      httpAttributes:
        httpMethod: POST
    dollarsinvestment_com/{city}/{state}:
      urlQueryParams:
        propertyType: dropdown
      urlPathParams:
        city: city
        state: state
      httpAttributes:
        httpMethod: GET
    buildings_created_com/{residential_or_commercial}:
      urlPathParams:
        residential_or_commercial: residential_or_commercial
  suggestionRequests:
    population_density_com: com.freddiemac.housing.service.request.PopulationDensityRequest

mongo.connection.string:  mongodb+srv://housing:housingpassword@hackathon.udmsy.mongodb.net/housing?retryWrites=true&w=majority
google.maps.geocode.api.key: AIzaSyD6-iEqSntM5iCrI5Ucoj9XOTeqZ9qj8pE
google.maps.geocode.api.url: https://maps.googleapis.com/maps/api/geocode/json?address=
google.maps.geocode.api.reverse.url: https://maps.googleapis.com/maps/api/geocode/json?latlng=



