suggestion:
  suggestionData:
    population_density_com:
      urlQueryParams:
        numReturn: numReturn
      requestAttributes:
        location: location
        date: date
      httpAttributes:
        httpMethod: POST
    dollarsinvestment_com/{city}/{state}:
      urlQueryParams:
        propertyType: numReturn
      urlPathParams:
        city: city
        state: state
      httpAttributes:
        httpMethod: GET
  suggestionRequests:
    population_density_com: com.freddiemac.housing.service.request.PopulationDensityRequest

mongo.connection.string:  mongodb+srv://housing:housingpassword@alpaca.olrez.mongodb.net/alpaca?retryWrites=true&w=majority
